# Clean Data

### Adjustments:
1. Empty Data
    1. FULL_COUNT (Y/N)
    2. ONEWAY_FLAG
2. Removals
    1. REGION (Redundant)
    2. REGION_CODE (Redundant)
    3. COUNTY_CODE (Redundant)
    4. STATION (Redundant)
    5. CCSTA (Mostly Empty)
    6. AXLE_FACTOR (Irrelevant)
    7. EST_FC_AXLE_FACTR (Irrelevant)
    8. EST_RG_FC_AXLE_FACTR (Irrelevant)
    9. Any date data (Irrelevant)
    10. AVG_K_FACTOR (Redundant)
    11. AVG_D_FACTOR (Redundant)
    12. DD_ID (Idk what it is)

In [1]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Load the Excel file
df = pd.read_excel("Count_Statistics_2021.xlsx")

# Save as CSV
df.to_csv("Count_Statistics_2021_CSV.csv", index=False)  # index=False prevents adding an extra index column

C:\Users\chris\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [3]:
csv_file_path = './Count_Statistics_2020_CSV.csv'
full_data = pd.read_csv(csv_file_path)
trimmed_data = pd.read_csv(csv_file_path)

#### Columns to be Removed

In [4]:
removed_columns = ([
    #'REGION',
    'REGION_CODE',
    'COUNTY_CODE',
    'STATION',
    'CCSTA',
    'AXLE_FACTOR',
    'EST_FC_AXLE_FACTR',
    'EST_RG_FC_AXLE_FACTR',
    'CALCULATION_YEAR',
    'YEAR_LAST_ACT',
    'MONTH_LAST_ACT',
    'DAY_LAST_ACT',
    'YEAR_2LAST_ACT',
    'AADT_2LAST_ACT',
    'YEAR_3LAST_ACT',
    'AADT_3LAST_ACT',
    'YEAR_4LAST_ACT',
    'AADT_4LAST_ACT',
    'CLASS_COUNT_YR',
    'CLASS_COUNT_MONTH',
    'CLASS_COUNT_DAY',
    'SPEED_COUNT_YR',
    'CLASS_EST_YR',
    'DD_ID',
    'AVG_K_FACTOR',
    'AVG_D_FACTOR',
    'FG',
    'AVG_WKDAY_F3_13',
    'ACT_AVG_CU_PERC',
    'ACT_AVG_BUS_PERC',
    'AVG_WKDAY_F5_7',
    'SU_PEAK',
    'CU_PEAK',
    'PH_PERC_F1',
    'PH_PERC_F2',
    'PH_PERC_F3',
    'PH_PERC_F4',
    'PH_PERC_F4_7',
    'PH_PERC_F5_7',
    'PH_PERC_F8_13',
    'PH_PERC_F4_13',
    'EST_RG_FC_SU',
    'EST_RG_FC_CU',
    'EST_RG_FC_TRUCK',
    'EST_RG_FC_SU_PEAK',
    'EST_RG_FC_CU_PEAK',
    'EST_RG_FC_PERC_F1',
    'EST_RG_FC_PH_PERC_F1',
    'EST_RG_FC_PH_PERC_F2',
    'EST_RG_FC_PH_PERC_F3',
    'EST_RG_FC_PH_PERC_F4',
    'EST_RG_FC_PH_PERC_F4_7',
    'EST_RG_FC_PH_PERC_F5_7',
    'EST_RG_FC_PH_PERC_F8_13',
    'EST_RG_FC_PH_PERC_F4_13',
    'EST_FC_SU',
    'EST_FC_CU',
    'EST_FC_TRUCK',
    'EST_FC_SU_PEAK',
    'EST_FC_CU_PEAK',
    'EST_FC_PH_PERC_F1',
    'EST_FC_PH_PERC_F2',
    'EST_FC_PH_PERC_F3',
    'EST_FC_PH_PERC_F4',
    'EST_FC_PH_PERC_F4_7',
    'EST_FC_PH_PERC_F5_7',
    'EST_FC_PH_PERC_F8_13',
    'EST_FC_PH_PERC_F4_13',
    'DHV',
    'DDHV'
    ])

In [5]:
for column in removed_columns:
    if column in trimmed_data.columns:
        trimmed_data = trimmed_data.drop(column, axis=1)

In [6]:
print("Number of original columns:", full_data.shape[1])
print("Number of new columns:", trimmed_data.shape[1])

Number of original columns: 66
Number of new columns: 26

In [7]:
trimmed_data.head()

,COUNT_STATS_ID,REGION,COUNTY_FIPS,RCSTA,FC,FEDERAL_DIRECTION,FULL_COUNT,ONEWAY_FLAG,AE_FLAG,AADT,...,ACT_AVG_SU_PERC,ACT_AVG_MC_PERC,ACT_AVG_CAR_PERC,ACT_AVG_LT_PERC,SPEED_LIMIT,AVG_SPEED,PERC_SPEED_50,PERC_SPEED_85,EXCEEDING_55,EXCEEDING_65
0,40683112,11.0,85.0,61178.0,19,NaN,Y,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,40670154,1.0,115.0,186712.0,9,NaN,Y,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,40811025,2.0,53.0,246097.0,19,NaN,Y,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,40711771,7.0,19.0,717022.0,9,NaN,Y,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,40684858,7.0,45.0,736047.0,9,NaN,Y,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Merging Vehicle Count Percentages

#### Everyday Roadway Vehicles (Class F1 - F7)
ACT_AVG_MC_PERC – The percentage of Motorcycles, class F1, based on the average weekday
distribution of vehicle classes from the most recent vehicle classification count for the segment.
                                                                                 
ACT_AVG_CAR_PERC – The percentage of Passenger Vehicles, class F2, based on the average
weekday distribution of vehicle classes from the most recent vehicle classification count for the
segment.

ACT_AVG_LT_PERC – The percentage of Light Duty Trucks, class F3, based on the average
weekday distribution of vehicle classes from the most recent vehicle classification count for the
segment.

ACT_AVG_SU_PERC – Single Unit Truck and Bus percentage. The percentage of the total
vehicles in classes F4 through F7 based on the average weekday distribution of vehicle classes
from the most recent vehicle classification count for the segment.

#### Everyday Roadway Vehicles (Class F8 - F13)
** Needs Subtraction **

ACT_AVG_TRUCK_PERC – Truck percentage or Heavy Vehicle Percentage. The percentage of
the total vehicles in classes F4 through F13 based on the average weekday distribution of
vehicle classes from the most recent vehicle classification count for the segment.

In [8]:
trimmed_data['ACT_AVG_HEAVY_PERC'] = trimmed_data['ACT_AVG_TRUCK_PERC'] - trimmed_data['ACT_AVG_SU_PERC']
trimmed_data = trimmed_data.dropna(subset=['AADT'])

In [9]:
# Save the modified DataFrame back to a CSV
trimmed_data.to_csv('./Count_Statistics_2021_Trimmed_CSV.csv', index=False)

## Merging years to try to replace lost data

In [23]:
# Load your datasets
df1 = pd.read_csv("Count_Statistics_2022_Trimmed_CSV.csv")  # Latest year (keep all rows)
df2 = pd.read_csv("Count_Statistics_2021_Trimmed_CSV.csv")  # Previous year (fill missing values)

# Set index to 'COUNT_STATS_ID' (or any key column) to ensure correct matching
df1.set_index("COUNT_STATS_ID", inplace=True)
df2.set_index("COUNT_STATS_ID", inplace=True)

# Fill missing values in df1 using df2 (only fills NaNs, doesn't overwrite existing data)
df1.update(df2)

# Reset index if needed
df1.reset_index(inplace=True)

# Save the cleaned file
df1.to_csv("data_2022_filled.csv", index=False)

In [27]:
df = pd.read_csv("data_2022_filled.csv")  # Data with missing values
print(df["ACT_AVG_TRUCK_PERC"].isna().sum())

df2 = pd.read_csv("Count_Statistics_2022_Trimmed_CSV.csv")
print(df["ACT_AVG_TRUCK_PERC"].isna().sum())

66875
66875